server:
  port: 18830
  servlet:
    encoding:
      charset: UTF-8

jasypt:
  encryptor:
    password: qnpfzns590192N#$!na

jwt:
  secretKey: qpoweknfasdklfnasdfnewqornqpoweknfasdklfnasdfnewqornqpoweknfasdklfnasdfnewqornqpoweknfasdklfnasdfnewqornqpoweknfasdklfnasdfnewqornqpoweknfasdklfnasdfnewqorn
  tokenValidTime: 1800000
  refreshTokenTime: 3600000


spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(KDO718FX0Zs420L6+A7p34vaf4rJ7MN+hzHuBj7CVMkaGrr8OHvmIA==)
      username: ENC(xkR3N9xS8F2m68yQ5SxuiQ==)
      password: ENC(+OKoqfQo35Xvz4gIx60IMqt5y7xVxilE)
      maximum-pool-size: 5
      connection-timeout: 0

mybatis:
  mapper-locations: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true

  redis:
    port: 6379
    #    port: 62736
    host: localhost로

webInfo:
  startUrl: http://
  domain: localhost
  port: :7200
  commonUrl: /chb