export const SIGN_IN: string = '/sign-in';
export const CURRENT_USER_INFO: string = '/current-user';
export const SIGN_UP: string = '/sign-up';
export const CHECK_EXIST_USER: string = '/check-exist-user';
export const GET_CURRENT_USER_GENDER: string = '/currentUser-gender';
export const APPLY_COUPLE_ACCOUNT: string = '/apply-couple-account';
export const GET_USER_PROFILE: string = '/fetch-user-profile';
export const UPLOAD_PROFILE_IMAGE:string = '/upload-image';
export const ACCEPT_BE_COUPLE: string = '/accept-be-couple'